# Generated by Django 4.0.1 on 2022-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0002_remove_worktime_start_week_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='daydetail',
            name='time',
        ),
        migrations.AddField(
            model_name='daydetail',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
