# Generated by Django 4.0.1 on 2022-01-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0003_remove_daydetail_date_remove_daydetail_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabib.doctor'),
        ),
    ]
