# Generated by Django 4.0.1 on 2022-01-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0005_alter_worktime_monday_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved_apointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reserved_apointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reserved_apointment',
            name='work_time',
        ),
        migrations.AddField(
            model_name='reserved_apointment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserved_apointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabib.doctor'),
        ),
    ]
