# Generated by Django 4.0.1 on 2022-01-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0007_rename_reserved_apointment_reservedapointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='apointment_time',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='worktime',
            name='week_avalible',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
