# Generated by Django 4.0.1 on 2022-01-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0008_worktime_apointment_time_worktime_week_avalible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabib.user'),
        ),
        migrations.AlterField(
            model_name='reservedapointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabib.user'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabib.doctor'),
        ),
    ]
