# Generated by Django 4.0.1 on 2022-01-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0009_alter_doctor_user_alter_reservedapointment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabib.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabib.user'),
        ),
        migrations.AlterField(
            model_name='reservedapointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabib.doctor'),
        ),
        migrations.AlterField(
            model_name='reservedapointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabib.user'),
        ),
    ]
