# Generated by Django 4.0.1 on 2022-01-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0010_alter_daydetail_doctor_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daydetail', to='tabib.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='tabib.user'),
        ),
        migrations.AlterField(
            model_name='reservedapointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apointments', to='tabib.doctor'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to='tabib.doctor'),
        ),
    ]
